import asyncio
import threading
from collections.abc import Coroutine
from typing import Any, Literal

from insta_wizard.common.entities import (
    Account,
    Comment,
    DirectThread,
    FriendshipStatus,
    FriendshipStatusShort,
    SentDirectMessage,
    User,
)
from insta_wizard.common.entities.account import AccountSecurity
from insta_wizard.common.entities.media import AlbumPhotoItem, AlbumVideoItem, Media
from insta_wizard.common.interfaces import EmailCodeSignupProvider, PhoneSmsCodeProvider
from insta_wizard.common.logger import InstagramClientLogger
from insta_wizard.common.models.checkpoint import Checkpoint
from insta_wizard.common.models.proxy import ProxyInfo
from insta_wizard.common.transport.models import TransportSettings
from insta_wizard.mobile.client import MobileClient
from insta_wizard.mobile.common.command import Command, R
from insta_wizard.mobile.flows.register_account_email import RegisterAccountEmailFlowResult
from insta_wizard.mobile.flows.register_account_sms import RegisterAccountSMSFlowResult
from insta_wizard.mobile.models.android_device_info import AndroidDeviceInfo
from insta_wizard.mobile.models.challenge import ChallengeRequiredData
from insta_wizard.mobile.models.local_data import MobileClientLocalData
from insta_wizard.mobile.models.state import MobileClientState
from insta_wizard.mobile.models.version import InstagramAppVersion
from insta_wizard.mobile.responses.account.account_check_phone_number import (
    AccountCheckPhoneNumberResponse,
)
from insta_wizard.mobile.responses.account.account_create_validated import (
    AccountCreateValidatedResponse,
)
from insta_wizard.mobile.responses.account.account_get_presence_disabled import (
    AccountGetPresenceDisabledResponse,
)
from insta_wizard.mobile.responses.account.account_send_confirm_email import (
    AccountSendConfirmEmailResponse,
)
from insta_wizard.mobile.responses.account.account_send_confirm_phone_number import (
    AccountSendConfirmPhoneNumberResponse,
)
from insta_wizard.mobile.responses.account.account_send_signup_sms_code import (
    AccountSendSignupSmsCodeResponse,
)
from insta_wizard.mobile.responses.account.account_validate_signup_sms_code import (
    AccountValidateSignupSmsCodeResponse,
)
from insta_wizard.mobile.responses.clips.discover_stream import ClipsDiscoverStreamResponse
from insta_wizard.mobile.responses.direct.async_get_pending_requests_preview import (
    DirectV2AsyncGetPendingRequestsPreviewResponse,
)
from insta_wizard.mobile.responses.direct.create_group_thread import (
    DirectV2CreateGroupThreadResponse,
)
from insta_wizard.mobile.responses.direct.get_pending_requests_preview import (
    DirectV2GetPendingRequestsPreviewResponse,
)
from insta_wizard.mobile.responses.direct.get_presence import DirectV2GetPresenceResponse
from insta_wizard.mobile.responses.direct.get_presence_active_now import (
    DirectV2GetPresenceActiveNowResponse,
)
from insta_wizard.mobile.responses.direct.has_interop_upgraded import (
    DirectV2HasInteropUpgradedResponse,
)
from insta_wizard.mobile.responses.direct.ranked_recipients import DirectV2RankedRecipientsResponse
from insta_wizard.mobile.responses.feed.reels_tray import FeedGetReelsTrayResponse
from insta_wizard.mobile.responses.news.inbox import NewsInboxResponse
from insta_wizard.mobile.responses.notifications.badge import NotificationsBadgeResponse
from insta_wizard.mobile.responses.notifications.get_notification_settings import (
    NotificationsGetNotificationSettingsResponse,
)
from insta_wizard.mobile.responses.user.account_details import UserAccountDetailsResponse
from insta_wizard.mobile.responses.user.get_limited_interactions_reminder import (
    UserGetLimitedInteractionsReminderResponse,
)
from insta_wizard.mobile.responses.user.web_profile_info import UserWebProfileInfoResponse

class SyncAccountSection:
    def get_current_user(self) -> Account: ...
    def get_security_info(self) -> AccountSecurity: ...
    def edit_profile(
        self,
        username: str,
        first_name: str,
        biography: str,
        external_url: str,
        email: str,
        phone_number: str,
        gender: str,
    ) -> None: ...
    def update_profile_name(self, first_name: str) -> None: ...
    def set_bio(self, bio_text: str) -> None: ...
    def set_profile_picture(self, upload_id: object) -> None: ...
    def get_presence_disabled(self) -> AccountGetPresenceDisabledResponse: ...
    def login(self, username: str, password: str) -> None: ...
    def logout(self) -> None: ...
    def check_phone_number(self, phone_number: str) -> AccountCheckPhoneNumberResponse: ...
    def send_signup_sms_code(self, phone_number: str) -> AccountSendSignupSmsCodeResponse: ...
    def validate_signup_sms_code(
        self, phone_number: str, code: int | str
    ) -> AccountValidateSignupSmsCodeResponse: ...
    def get_username_suggestions(self, username: str) -> object: ...
    def create_validated(
        self,
        username: str,
        password: str,
        first_name: str,
        code: int | str,
        phone_number: str,
        day: int,
        month: int,
        year: int,
        tos_version: str = ...,
    ) -> AccountCreateValidatedResponse: ...
    def send_confirm_email(self, email: str) -> AccountSendConfirmEmailResponse: ...
    def send_confirm_phone_number(
        self, phone_number: str
    ) -> AccountSendConfirmPhoneNumberResponse: ...

class SyncClipSection:
    def get_stream(self) -> ClipsDiscoverStreamResponse: ...

class SyncDirectSection:
    def get_inbox(self) -> list[DirectThread]: ...
    def get_pending(self) -> DirectV2GetPendingRequestsPreviewResponse: ...
    def get_presence(self) -> DirectV2GetPresenceResponse: ...
    def get_presence_active_now(self) -> DirectV2GetPresenceActiveNowResponse: ...
    def get_ranked_recipients(
        self, mode: Literal["raven", "reshare"] = ...
    ) -> DirectV2RankedRecipientsResponse: ...
    def create_group_thread(
        self, recipient_users: list[str], thread_title: str
    ) -> DirectV2CreateGroupThreadResponse: ...
    def approve_thread(self, thread_id: str) -> None: ...
    def approve_multiple_threads(self, thread_ids: list[str]) -> None: ...
    def decline_thread(self, thread_id: str) -> None: ...
    def decline_multiple_threads(self, thread_ids: list[str]) -> None: ...
    def decline_all_threads(self, thread_ids: list[str]) -> None: ...
    def delete_thread_item(self, thread_id: str, item_id: str) -> None: ...
    def mark_thread_item_seen(self, thread_id: str, item_id: str) -> None: ...
    def leave_thread(self, thread_id: str) -> None: ...
    def mute_thread(self, thread_id: str) -> None: ...
    def unmute_thread(self, thread_id: str) -> None: ...
    def hide_thread(self, thread_id: str) -> None: ...
    def update_thread_title(self, thread_id: str, title: str) -> None: ...
    def add_user_to_thread(self, thread_id: str, user_ids: list[str | int]) -> None: ...
    def send_message(self, user_ids: list[str], text: str) -> SentDirectMessage: ...
    def send_reaction(
        self,
        thread_ids: list[str],
        item_id: str,
        reaction_type: str,
        reaction_action_source: str,
    ) -> None: ...
    def delete_thread_items_locally(self, thread_id: str, item_ids: list[str]) -> None: ...
    def get_pending_async(self) -> DirectV2AsyncGetPendingRequestsPreviewResponse: ...
    def has_interop_upgraded(self) -> DirectV2HasInteropUpgradedResponse: ...

class SyncFeedSection:
    def get_stories_tray(self) -> FeedGetReelsTrayResponse: ...

class SyncFriendshipsSection:
    def follow(self, user_id: str) -> None: ...
    def unfollow(self, user_id: str) -> None: ...
    def remove_follower(self, user_id: str) -> None: ...
    def get_user_followers(
        self, user_id: str, query: str | None = ..., max_id: int | None = ...
    ) -> list[User]: ...
    def get_user_following(
        self, user_id: str, query: str | None = ..., max_id: int | None = ...
    ) -> list[User]: ...
    def get_status(self, user_id: str) -> FriendshipStatus: ...
    def get_status_many(self, user_ids: list[str]) -> dict[str, FriendshipStatusShort]: ...

class SyncLiveSection:
    def get_good_time_for_live(self) -> None: ...

class SyncMediaSection:
    def publish_photo(self, image: bytes, caption: str = ...) -> Media: ...
    def publish_story_photo(self, image: bytes) -> Media: ...
    def publish_video(
        self,
        video: bytes,
        caption: str = ...,
        thumbnail: bytes | None = ...,
        transcode: bool = ...,
        fit_mode: Literal["pad", "crop"] = ...,
    ) -> Media: ...
    def publish_story_video(
        self,
        video: bytes,
        thumbnail: bytes | None = ...,
        transcode: bool = ...,
        fit_mode: Literal["pad", "crop"] = ...,
    ) -> Media: ...
    def publish_reel(
        self,
        video: bytes,
        caption: str = ...,
        thumbnail: bytes | None = ...,
        share_to_feed: bool = ...,
        audio_muted: bool = ...,
        transcode: bool = ...,
        fit_mode: Literal["pad", "crop"] = ...,
    ) -> Media: ...
    def publish_carousel(
        self, items: list[AlbumPhotoItem | AlbumVideoItem], caption: str = ...
    ) -> Media: ...
    def get_info(self, media_id: str) -> Media: ...
    def like(self, media_id: str) -> None: ...
    def unlike(self, media_id: str) -> None: ...
    def delete(self, media_id: str) -> None: ...
    def edit(self, media_id: str, caption_text: str) -> None: ...
    def save(self, media_id: str) -> None: ...
    def unsave(self, media_id: str) -> None: ...
    def get_likers(self, media_id: str) -> list[User]: ...
    def get_comments(
        self, media_id: str, min_id: str | None = ..., max_id: str | None = ...
    ) -> list[Comment]: ...
    def add_comment(
        self, media_id: str, text: str, replied_to_comment_id: str | None = ...
    ) -> Comment: ...
    def delete_comments(self, media_id: str, comment_ids: list[str]) -> None: ...
    def like_comment(self, comment_id: str) -> None: ...
    def unlike_comment(self, comment_id: str) -> None: ...
    def get_blocked(self) -> list[str]: ...

class SyncNewsSection:
    def get_inbox(self) -> NewsInboxResponse: ...

class SyncNotificationSection:
    def get_settings(self) -> NotificationsGetNotificationSettingsResponse: ...
    def get_badge(self) -> NotificationsBadgeResponse: ...

class SyncUserSection:
    def get_info(self, user_id: str) -> User: ...
    def get_info_by_username(self, username: str) -> User: ...
    def get_web_profile(self, username: str) -> UserWebProfileInfoResponse: ...
    def search(self, query: str, count: int = ...) -> list[User]: ...
    def get_details(self, user_id: str | int) -> UserAccountDetailsResponse: ...
    def get_limited_interactions_reminder(self) -> UserGetLimitedInteractionsReminderResponse: ...

class SyncChallengeSection:
    def get_challenge_info(self, challenge_data: ChallengeRequiredData) -> Checkpoint | None: ...
    def determine_checkpoint_by_challenge_info(
        self, challenge_info: object, challenge_bloks: dict
    ) -> Checkpoint: ...
    def pass_vetted_delta(self, choice: str = ...) -> None: ...
    def pass_scraping_warning(self) -> None: ...

class SyncRegistrationSection:
    def register_account_sms(
        self,
        username: str,
        password: str,
        first_name: str,
        day: int,
        month: int,
        year: int,
        phone_code_provider: PhoneSmsCodeProvider,
    ) -> RegisterAccountSMSFlowResult: ...
    def register_account_email(
        self,
        username: str,
        password: str,
        first_name: str,
        day: int,
        month: int,
        year: int,
        email_code_provider: EmailCodeSignupProvider,
    ) -> RegisterAccountEmailFlowResult: ...

class SyncSection:
    _s: object
    _run: Any
    def __init__(self, async_section: object, run_fn: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class SyncMobileClient:
    _loop: asyncio.AbstractEventLoop
    _thread: threading.Thread
    _async_client: MobileClient
    state: MobileClientState
    account: SyncAccountSection
    users: SyncUserSection
    friendships: SyncFriendshipsSection
    feed: SyncFeedSection
    direct: SyncDirectSection
    media: SyncMediaSection
    notifications: SyncNotificationSection
    news: SyncNewsSection
    live: SyncLiveSection
    clips: SyncClipSection
    challenge: SyncChallengeSection
    registration: SyncRegistrationSection

    def __init__(
        self,
        device: AndroidDeviceInfo | None = ...,
        version: InstagramAppVersion = ...,
        local_data: MobileClientLocalData | None = ...,
        proxy: ProxyInfo | None = ...,
        transport_settings: TransportSettings | None = ...,
        logger: InstagramClientLogger | None = ...,
    ) -> None: ...
    @staticmethod
    async def _create_async_client(**kwargs: Any) -> MobileClient: ...
    def _run(self, coro: Coroutine[Any, Any, Any]) -> Any: ...
    def __enter__(self) -> SyncMobileClient: ...
    def __exit__(self, *_: object) -> None: ...
    def execute(self, command: Command[R]) -> R: ...
    def close(self) -> None: ...
    def set_proxy(self, proxy: ProxyInfo | None) -> None: ...
    def get_local_data(self) -> MobileClientLocalData: ...
    def dump_state(self) -> dict: ...
    def load_state(self, state: dict) -> None: ...
    def login(self, username: str, password: str) -> None: ...
    def logout(self) -> None: ...
