"""
AUTOGENERATED FILE. DO NOT EDIT MANUALLY.
Run: python tools/gen_instagram_web_exports.py

Public exports for insta_wizard.web.commands.
"""

from .account.check_age_eligibility import CheckAgeEligibility
from .account.edit import AccountsEdit
from .account.edit_web_form_data import AccountsEditWebFormData
from .account.get_email_signup_page import GetEmailSignupPage
from .account.login_ajax import AccountsLoginAjax
from .account.logout_ajax import AccountsLogoutAjax
from .account.recovery_send_ajax import AccountRecoverySendAjax
from .account.send_sms_code_ajax import SendSignupSmsCodeAjax
from .account.web_create_ajax import WebCreateAjax
from .account.web_create_ajax_attempt import WebCreateAjaxAttempt
from .auth_platform.code_entry_view_query import AuthPlatformCodeEntryViewQuery
from .auth_platform.send_code_again import UseAuthPlatformSendCodeAgainMutation
from .auth_platform.submit_code import UseAuthPlatformSubmitCodeMutation
from .challenge.bloks_navigation import BloksNavigationTakeChallenge
from .challenge.challenge_web import ChallengeWeb
from .challenge.challenge_web_action import ChallengeWebAction
from .comments.comments_add import CommentsAdd
from .comments.comments_like import CommentsLike
from .comments.comments_unlike import CommentsUnlike
from .friendships.create import FriendshipsCreate
from .friendships.destroy import FriendshipsDestroy
from .friendships.follow import FriendshipsFollow
from .likes.likes_like import LikesLike
from .likes.likes_unlike import LikesUnlike
from .navigation.get_home_page import GetInstagramHomePage
from .navigation.get_shared_data import GetSharedData
from .navigation.get_web_mid import GetWebMid
from .navigation.navigate import Navigate
from .search.polaris_search_box import PolarisSearchBoxRefetchableQuery

__all__ = [
    "CheckAgeEligibility",
    "AccountsEdit",
    "AccountsEditWebFormData",
    "GetEmailSignupPage",
    "AccountsLoginAjax",
    "AccountsLogoutAjax",
    "AccountRecoverySendAjax",
    "SendSignupSmsCodeAjax",
    "WebCreateAjax",
    "WebCreateAjaxAttempt",
    "AuthPlatformCodeEntryViewQuery",
    "UseAuthPlatformSendCodeAgainMutation",
    "UseAuthPlatformSubmitCodeMutation",
    "BloksNavigationTakeChallenge",
    "ChallengeWeb",
    "ChallengeWebAction",
    "CommentsAdd",
    "CommentsLike",
    "CommentsUnlike",
    "FriendshipsCreate",
    "FriendshipsDestroy",
    "FriendshipsFollow",
    "LikesLike",
    "LikesUnlike",
    "GetInstagramHomePage",
    "GetSharedData",
    "GetWebMid",
    "Navigate",
    "PolarisSearchBoxRefetchableQuery",
]
