import asyncio
import threading
from collections.abc import Coroutine
from typing import Any

from insta_wizard.common.logger import InstagramClientLogger
from insta_wizard.common.models.checkpoint import Checkpoint
from insta_wizard.common.models.proxy import ProxyInfo
from insta_wizard.common.transport.models import TransportSettings
from insta_wizard.web.client import WebClient
from insta_wizard.web.common.command import Command, R
from insta_wizard.web.models.device_info import BrowserDeviceInfo
from insta_wizard.web.models.local_data import WebClientLocalData
from insta_wizard.web.models.other import CheckpointRequiredErrorData
from insta_wizard.web.models.state import WebClientState
from insta_wizard.web.responses.account.check_age_eligibility import CheckAgeEligibilityResponse
from insta_wizard.web.responses.account.edit_web_form_data import AccountsEditWebFormDataResponse
from insta_wizard.web.responses.account.recovery_send_ajax import AccountRecoverySendAjaxResponse
from insta_wizard.web.responses.account.send_sms_code_ajax import SendSignupSmsCodeAjaxResponse
from insta_wizard.web.responses.account.web_create_ajax import WebCreateAjaxResponse
from insta_wizard.web.responses.account.web_create_ajax_attempt import WebCreateAjaxAttemptResponse
from insta_wizard.web.responses.comments.comments_add import CommentsAddResponse
from insta_wizard.web.responses.navigation.get_shared_data import GetSharedDataResponse

class SyncSection:
    _s: object
    _run: Any
    def __init__(self, async_section: object, run_fn: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class SyncAccountSection:
    def edit(
        self,
        biography: str | None,
        chaining_enabled: bool,
        external_url: str | None,
        first_name: str,
        username: str,
    ) -> None: ...
    def get_edit_form_data(self) -> AccountsEditWebFormDataResponse: ...
    def check_age_eligibility(
        self, day: int, month: int, year: int
    ) -> CheckAgeEligibilityResponse: ...
    def recovery_send_ajax(self, email_or_username: str) -> AccountRecoverySendAjaxResponse: ...
    def login_ajax(self, username: str, enc_password: str, jazoest: str) -> None: ...
    def send_sms_code_ajax(
        self, phone_number: str, captcha_token: str | None = ...
    ) -> SendSignupSmsCodeAjaxResponse: ...
    def web_create_ajax(
        self,
        username: str,
        password: str,
        first_name: str,
        phone_number: str,
        day: int,
        month: int,
        year: int,
        sms_code: int | str,
    ) -> WebCreateAjaxResponse: ...
    def web_create_ajax_attempt(
        self,
        username: str,
        password: str,
        first_name: str,
        phone_number: str,
    ) -> WebCreateAjaxAttemptResponse: ...

class SyncChallengeSection:
    def get_challenge_info(
        self, challenge_required_data: CheckpointRequiredErrorData
    ) -> Checkpoint: ...
    def determine_checkpoint_by_url(self, url: str, challenge_info: dict) -> Checkpoint: ...
    def pass_vetted_delta(self, choice: str = ...) -> None: ...
    def pass_scraping_warning(self) -> None: ...

class SyncCommentsSection:
    def add(
        self, media_id: str, text: str, replied_to_comment_id: str | None = ...
    ) -> CommentsAddResponse: ...
    def like(self, comment_id: str) -> None: ...
    def unlike(self, comment_id: str) -> None: ...

class SyncFriendshipsSection:
    def create(self, user_id: str) -> None: ...
    def follow(self, user_id: str) -> None: ...
    def unfollow(self, user_id: str) -> None: ...

class SyncLikesSection:
    def like(self, media_id: str) -> None: ...
    def unlike(self, media_id: str) -> None: ...

class SyncNavigationSection:
    def navigate(self, url: str) -> str: ...
    def get_home_page(self) -> str: ...
    def get_shared_data(self) -> GetSharedDataResponse: ...
    def get_web_mid(self) -> str: ...
    def get_email_signup_page(self) -> str: ...

class SyncUserSection:
    def user_short_gql(self, user_id: str) -> dict: ...
    def web_profile_info(self, username: str) -> dict: ...

class SyncWebClient:
    _loop: asyncio.AbstractEventLoop
    _thread: threading.Thread
    _async_client: WebClient
    state: WebClientState
    account: SyncAccountSection
    challenge: SyncChallengeSection
    comments: SyncCommentsSection
    friendships: SyncFriendshipsSection
    likes: SyncLikesSection
    navigation: SyncNavigationSection
    user: SyncUserSection

    def __init__(
        self,
        device: BrowserDeviceInfo | None = ...,
        local_data: WebClientLocalData | None = ...,
        proxy: ProxyInfo | None = ...,
        transport_settings: TransportSettings | None = ...,
        logger: InstagramClientLogger | None = ...,
    ) -> None: ...
    @staticmethod
    async def _create_async_client(**kwargs: Any) -> WebClient: ...
    def _run(self, coro: Coroutine[Any, Any, Any]) -> Any: ...
    def __enter__(self) -> SyncWebClient: ...
    def __exit__(self, *_: object) -> None: ...
    def execute(self, command: Command[R]) -> R: ...
    def close(self) -> None: ...
    def set_proxy(self, proxy: ProxyInfo | None) -> None: ...
    def get_local_data(self) -> WebClientLocalData: ...
    def get_cookies(self) -> dict: ...
    def set_cookies(self, cookies: dict) -> None: ...
    def dump_state(self) -> dict: ...
    def load_state(self, state: dict) -> None: ...
    def initialize_state(self) -> None: ...
    def login(self, username: str, password: str) -> None: ...
    def logout(self) -> None: ...
